### ISSUE TITLE
运行不起来啊

### ISSUE THREAD

**Issue by eternal8080** [CircleRadon/TokenPacker#16]
(tokenpacker) (base) root@hr-a6000-129-65:/mnt/wangpeijie/multi-doc/TokenPacker# python /mnt/wangpeijie/multi-doc/TokenPacker/llava/eval/run_llava.py
Traceback (most recent call last):
  File "/mnt/wangpeijie/multi-doc/TokenPacker/llava/eval/run_llava.py", line 4, in <module>
    from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN
  File "/mnt/wangpeijie/multi-doc/TokenPacker/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/wangpeijie/multi-doc/TokenPacker/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/mnt/wangpeijie/multi-doc/TokenPacker/llava/model/language_model/llava_llama.py", line 142, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/mnt/wangpeijie/miniconda3/envs/tokenpacker/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1153, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/mnt/wangpeijie/miniconda3/envs/tokenpacker/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 846, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.

**Comment by CircleRadon** [comment]
@eternal8080 Sorry for late reply. We use the version of transformers==4.31.0, please retry the process using this specific version.
